In [2]:
#Load all all of the packages we need.

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import cenpy
from cenpy import products

In [3]:
sandagvmt=gpd.read_file('San_Diego_Region_SB743_VMT_Maps/San_Diego_Region_SB743_VMT_Maps.shp') #Load in the Database.

## Subsetting our data. 

We are concerned about data on the Census Tract level, for the estimated year 2025, using the most recently developed SANDAG model. We also subset for residents and VMT per capita to best match SB 743.

In [4]:
gdf = sandagvmt[(sandagvmt['geo']=='Census Tract') & (sandagvmt['vmt_year']==2025) & (sandagvmt['version']=='ABM2+ / 2021 RP')&(sandagvmt['vmt_type']=='Residents') & (sandagvmt['vmt_metric']=='Per Capita')]

## Collect Census Data

#### Variables we're interested in

- population_race="B03002_001", #race/ethnic total
- race_white="B03002_003", #white NH alone
- race_black="B03002_004", #black/african american NH
- race_amindian="B03002_005", #american indian/alaska native NH
- race_asian="B03002_006", #asian NH
- race_pacisl="B03002_007", #native hawaiian and other pacific islander NH
- race_other="B03002_008", #some other race alone NH
- race_twoplus="B03002_009", #two or more races NH
- race_hisp ="B03002_012", #total Hisp
- median_income="B25119_001" #median income

In [5]:
#troubleshooting cenpy issues
import requests
#get=NAME,B01001_001E,B01001H_001E,B03002_001,B03002_003,B03002_004,B03002_005,B03002_006,B03002_007,B03002_008,B03002_009,B03002_012,B25119_001
r = requests.get('https://api.census.gov/data/2019/acs/acs5?get=NAME,B01001_001E,B01001H_001E,B03002_001E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,B03002_012E,B25119_001E&for=county')
censusdata = r.json()
df=pd.DataFrame(censusdata[1:], columns=censusdata[0])
df.head()

,NAME,B01001_001E,B01001H_001E,B03002_001E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,B03002_012E,B25119_001E,state,county
0,"Fayette County, Illinois",21565,19868,21565,1007,68,116,28,0,75,403,46650,17,051
1,"Logan County, Illinois",29003,25049,29003,1984,35,218,2,24,706,985,57308,17,107
2,"Saline County, Illinois",23994,21957,23994,632,53,173,54,12,685,428,44090,17,165
3,"Lake County, Illinois",701473,432361,701473,45923,907,53654,196,1324,14967,152141,89427,17,097
4,"Massac County, Illinois",14219,12547,14219,830,6,29,0,0,388,419,47481,17,127

In [6]:
df['pc_nonHispanicWhite'] = df.B01001H_001E.astype(float) / df.B01001_001E.astype(float) * 100 
ca=df[df['state']=='06']
sd=ca[ca['county']=='073']
sd

,NAME,B01001_001E,B01001H_001E,B03002_001E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,B03002_012E,B25119_001E,state,county,pc_nonHispanicWhite
204,"San Diego County, California",3316073,1510756,3316073,156084,12474,385657,12747,6560,114278,1117517,78980,06,073,45.558587

In [73]:
sd.rename(columns={"B01001_001E":"total_pop","B01001H_001E":"white_nh","B25119_001E": "median_income", "B03002_001E": "total_race","B03002_004E":"black_nh", "B03002_005E":"native_na_alaska_nh","B03002_006E":"asian_nh","B03002_007E":"native_hi_pi_nh","B03002_008E":"other_race","B03002_009E":"mixed_race","B03002_012E": "total_hisp",}, inplace=True)

sd['pc_Black'] = sd.black_nh.astype(float) / sd.total_pop.astype(float) * 100 
sd['pc_amindian'] = sd.native_na_alaska_nh.astype(float) / sd.total_pop.astype(float) * 100 
sd['pc_pacislander'] = sd.native_hi_pi_nh.astype(float) / sd.total_pop.astype(float) * 100
sd['pc_asian'] = sd.asian_nh.astype(float) / sd.total_pop.astype(float) * 100 
sd['pc_mixedrace'] = sd.mixed_race.astype(float) / sd.total_pop.astype(float) * 100 
sd['pc_hispanic'] = sd.total_hisp.astype(float) / sd.total_pop.astype(float) * 100 
sd['pc_other_race'] = sd.other_race.astype(float) / sd.total_pop.astype(float) * 100

/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd.rename(columns={"B01001_001E":"total_pop","B01001H_001E":"white_nh","B25119_001E": "median_income", "B03002_001E": "total_race","B03002_004E":"black_nh", "B03002_005E":"native_na_alaska_nh","B03002_006E":"asian_nh","B03002_007E":"native_hi_pi_nh","B03002_008E":"other_race","B03002_009E":"mixed_race","B03002_012E": "total_hisp",}, inplace=True)
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_Black'] = sd.black_nh.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_amindian'] = sd.native_na_alaska_nh.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_pacislander'] = sd.native_hi_pi_nh.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_asian'] = sd.asian_nh.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_mixedrace'] = sd.mixed_race.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_hispanic'] = sd.total_hisp.astype(float) / sd.total_pop.astype(float) * 100
/var/folders/8n/y7s3wtvx1x19_xxnxrv8njb80000gn/T/ipykernel_35047/86215608.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sd['pc_other_race'] = sd.other_race.astype(float) / sd.total_pop.astype(float) * 100

,NAME,total_pop,white_nh,total_race,black_nh,native_na_alaska_nh,asian_nh,native_hi_pi_nh,other_race,mixed_race,...,state,county,pc_nonHispanicWhite,pc_Black,pc_amindian,pc_pacislander,pc_asian,pc_mixedrace,pc_hispanic,pc_other_race
204,"San Diego County, California",3316073,1510756,3316073,156084,12474,385657,12747,6560,114278,...,06,073,45.558587,4.706893,0.376168,0.3844,11.629931,3.446185,33.700012,0.197824

In [7]:
sd.columns

Index(['NAME', 'B01001_001E', 'B01001H_001E', 'B03002_001E', 'B03002_004E',
       'B03002_005E', 'B03002_006E', 'B03002_007E', 'B03002_008E',
       'B03002_009E', 'B03002_012E', 'B25119_001E', 'state', 'county',
       'pc_nonHispanicWhite'],
      dtype='object')

In [9]:
#CENPY attempt
acs = cenpy.products.ACS()

sdcen = products.ACS(2019).from_county('San Diego, CA', level='tract',
                                     variables=['B01001H_001E','B01001_001E'])

C:\Users\Aaron\anaconda3\envs\environment_2\lib\site-packages\cenpy\tiger.py:186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if kwargs.get("returnGeometry", "true") is "false":
C:\Users\Aaron\anaconda3\envs\environment_2\lib\site-packages\cenpy\tiger.py:186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if kwargs.get("returnGeometry", "true") is "false":

KeyError: 'Response from API is malformed. You may have submitted too many queries, formatted the request incorrectly, or experienced significant network connectivity issues. Check to make sure that your inputs, like placenames, are spelled correctly, and that your geographies match the level at which you intend to query. The original error from the Census is:\\n(API ERROR 400:Unable to complete operation.([]))'